<?php
declare(strict_types=1);
require_once __DIR__.'/../../config/bootstrap.php';

$action=$_GET['action'] ?? 'me'; $method=$_SERVER['REQUEST_METHOD'];

if($action==='health'){try{$pdo=db();$pdo->query('SELECT 1');json_out(['ok'=>true,'app'=>'first-british-course-system','time'=>gmdate('c'),'php'=>PHP_VERSION]);}catch(Throwable $e){json_out(['ok'=>false,'error'=>'Database unavailable'],503);}}
if($action==='me'){ json_out(['authenticated'=>!!current_user(),'user'=>current_user(),'csrf'=>csrf(),'settings'=>['center_name'=>setting('center_name'),'center_name_ar'=>setting('center_name_ar')]]); }
if($action==='csrf'){ json_out(['csrf'=>csrf()]); }

if($action==='login' && $method==='POST'){
    require_csrf(); $d=body(); $login=trim((string)($d['login']??''));$pw=(string)($d['password']??'');
    $s=db()->prepare('SELECT * FROM users WHERE username=? OR email=? LIMIT 1');$s->execute([$login,$login]);$u=$s->fetch();
    if(!$u || $u['status']!=='active' || !$u['password_hash'] || !password_verify($pw,$u['password_hash'])){if($u)login_log((int)$u['id'],'failed','password');usleep(250000);json_out(['error'=>'Invalid username/email or password'],401);}
    session_regenerate_id(true);$_SESSION['user_id']=$u['id'];csrf();db()->prepare('UPDATE users SET last_login_at=NOW() WHERE id=?')->execute([$u['id']]);login_log((int)$u['id'],'success','password');audit('LOGIN','user',(int)$u['id']);json_out(['ok'=>true,'user'=>current_user(),'csrf'=>csrf()]);
}
if($action==='logout' && $method==='POST'){require_csrf();if($u=current_user())audit('LOGOUT','user',(int)$u['id']);$_SESSION=[];if(ini_get('session.use_cookies')){ $p=session_get_cookie_params();setcookie(session_name(),'',['expires'=>time()-42000,'path'=>$p['path'],'domain'=>$p['domain'],'secure'=>$p['secure'],'httponly'=>$p['httponly'],'samesite'=>$p['samesite']??'Lax']); }session_destroy();json_out(['ok'=>true]);}

if($action==='google_start'){
    if(!envv('GOOGLE_CLIENT_ID')){header('Location: /?google_error=not_configured');exit;}
    $state=bin2hex(random_bytes(24));$_SESSION['oauth_state']=$state;$params=http_build_query(['client_id'=>envv('GOOGLE_CLIENT_ID'),'redirect_uri'=>envv('GOOGLE_REDIRECT_URI'),'response_type'=>'code','scope'=>'openid email profile','state'=>$state,'prompt'=>'select_account']);header('Location: https://accounts.google.com/o/oauth2/v2/auth?'.$params);exit;
}
if($action==='google_callback'){
    $state=$_GET['state']??'';if(!$state||!hash_equals((string)($_SESSION['oauth_state']??''),(string)$state))die('Invalid OAuth state.');$code=$_GET['code']??'';if(!$code)die('Google sign-in cancelled.');
    $ch=curl_init('https://oauth2.googleapis.com/token');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_POSTFIELDS=>http_build_query(['code'=>$code,'client_id'=>envv('GOOGLE_CLIENT_ID'),'client_secret'=>envv('GOOGLE_CLIENT_SECRET'),'redirect_uri'=>envv('GOOGLE_REDIRECT_URI'),'grant_type'=>'authorization_code'])]);$token=json_decode(curl_exec($ch),true);curl_close($ch);if(empty($token['access_token']))die('Google token exchange failed.');
    $ch=curl_init('https://openidconnect.googleapis.com/v1/userinfo');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token['access_token']]]);$info=json_decode(curl_exec($ch),true);curl_close($ch);if(empty($info['sub'])||empty($info['email']))die('Google profile unavailable.');
    $s=db()->prepare('SELECT * FROM users WHERE google_sub=? OR email=? LIMIT 1');$s->execute([$info['sub'],$info['email']]);$u=$s->fetch();
    if(!$u){$base=preg_replace('/[^a-z0-9_]/i','_',explode('@',$info['email'])[0]);$username=$base?:'user';$n=0;while(true){$try=$username.($n?:'');$q=db()->prepare('SELECT COUNT(*) FROM users WHERE username=?');$q->execute([$try]);if(!(int)$q->fetchColumn()){$username=$try;break;}$n++;}$q=db()->prepare('INSERT INTO users(google_sub,username,email,full_name,role,status,profile_complete) VALUES(?,?,?,?,\'student\',\'active\',0)');$q->execute([$info['sub'],$username,$info['email'],$info['name']??$username]);$uid=(int)db()->lastInsertId();$s=db()->prepare('SELECT * FROM users WHERE id=?');$s->execute([$uid]);$u=$s->fetch();}elseif(empty($u['google_sub'])){db()->prepare('UPDATE users SET google_sub=? WHERE id=?')->execute([$info['sub'],$u['id']]);}
    if($u['status']!=='active')die('This account is suspended.');session_regenerate_id(true);$_SESSION['user_id']=$u['id'];login_log((int)$u['id'],'success','google');audit('LOGIN','user',(int)$u['id']);header('Location: /');exit;
}

if($action==='onboarding' && $method==='POST'){
    $u=require_auth();require_csrf();$d=body();$username=trim((string)($d['username']??''));$password=(string)($d['password']??'');$full=trim((string)($d['full_name']??$u['full_name']));
    if(!preg_match('/^[A-Za-z0-9_\.\-]{3,80}$/',$username)||strlen($password)<10)json_out(['error'=>'Username must be 3-80 characters and password at least 10 characters'],422);
    try{db()->prepare('UPDATE users SET username=?,password_hash=?,full_name=?,profile_complete=1 WHERE id=?')->execute([$username,password_hash($password,PASSWORD_DEFAULT),$full,$u['id']]);audit('PROFILE_COMPLETE','user',(int)$u['id']);json_out(['ok'=>true]);}catch(Throwable $e){json_out(['error'=>'Username is already in use'],409);}
}

$u=require_auth();

$read=['dashboard','terms','holidays','levels','courses','trainers','students','schedule','audit','settings','login_history','archives','my_archive','term_days','print','enrollments','conflicts'];
if($method==='GET' && in_array($action,$read,true)){
    $pdo=db();
    if($action==='dashboard'){
        $counts=[];foreach(['courses','trainers','students','terms','schedule_entries'] as $t){$counts[$t]=(int)$pdo->query("SELECT COUNT(*) FROM $t")->fetchColumn();}$counts['conflicts']=(int)$pdo->query("SELECT COUNT(*) FROM enrollments e1 JOIN enrollments e2 ON e2.student_id=e1.student_id AND e2.term_id=e1.term_id AND e2.id>e1.id JOIN schedule_entries se1 ON se1.term_id=e1.term_id AND se1.term_course_id IN (SELECT id FROM term_courses WHERE course_id=e1.course_id AND term_id=e1.term_id) JOIN schedule_entries se2 ON se2.term_id=e2.term_id AND se2.term_course_id IN (SELECT id FROM term_courses WHERE course_id=e2.course_id AND term_id=e2.term_id) AND se2.session_date=se1.session_date AND se2.start_time < se1.end_time AND se2.end_time > se1.start_time WHERE e1.status='active' AND e2.status='active'")->fetchColumn();$counts['suspended_courses']=(int)$pdo->query("SELECT COUNT(*) FROM courses WHERE status='suspended'")->fetchColumn();
        $term=$pdo->query("SELECT * FROM terms ORDER BY start_date DESC LIMIT 1")->fetch();$recent=$pdo->query("SELECT a.id,a.action,a.entity,a.created_at,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 8")->fetchAll();json_out(['counts'=>$counts,'current_term'=>$term,'recent'=>$recent]);
    }
    if($action==='terms'){json_out(['data'=>$pdo->query('SELECT t.*, (SELECT COUNT(*) FROM term_courses tc WHERE tc.term_id=t.id) course_count FROM terms t ORDER BY t.start_date DESC')->fetchAll()]);}
    if($action==='holidays'){json_out(['data'=>$pdo->query('SELECT * FROM holidays ORDER BY holiday_date')->fetchAll()]);}
    if($action==='levels'){json_out(['data'=>$pdo->query('SELECT * FROM levels WHERE active=1 ORDER BY level_order')->fetchAll()]);}
    if($action==='courses'){json_out(['data'=>$pdo->query("SELECT c.*,(SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id AND e.status='active') student_count FROM courses c ORDER BY c.level_order,c.name")->fetchAll()]);}
    if($action==='trainers'){json_out(['data'=>$pdo->query('SELECT t.*,(SELECT COUNT(*) FROM schedule_entries s WHERE s.trainer_id=t.id AND s.status IN (\'approved\',\'published\')) assigned_count FROM trainers t ORDER BY t.full_name')->fetchAll()]);}
    if($action==='students'){json_out(['data'=>$pdo->query('SELECT s.*,TIMESTAMPDIFF(YEAR,s.date_of_birth,CURDATE()) age FROM students s ORDER BY s.full_name')->fetchAll()]);}
    if($action==='schedule'){
        $term=(int)($_GET['term_id']??0);$status=$_GET['status']??'';$sql="SELECT se.*,c.name course_name,c.code course_code,c.level_name,c.level_order,t.full_name trainer_name,tc.sessions_per_week,(SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id AND e.term_id=se.term_id AND e.status='active') student_count FROM schedule_entries se JOIN term_courses tc ON tc.id=se.term_course_id JOIN courses c ON c.id=tc.course_id LEFT JOIN trainers t ON t.id=se.trainer_id WHERE se.term_id=?";$args=[$term];if($status){$sql.=' AND se.status=?';$args[]=$status;}$sql.=' ORDER BY se.session_date,se.start_time,c.name';$s=$pdo->prepare($sql);$s->execute($args);json_out(['data'=>$s->fetchAll()]);
    }
    if($action==='audit'){require_auth(['super_admin','admin','auditor']);$limit=min(500,max(1,(int)($_GET['limit']??200)));$s=$pdo->query("SELECT a.*,u.username,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT $limit");json_out(['data'=>$s->fetchAll()]);}
    if($action==='login_history'){require_auth(['super_admin','admin','auditor']);$limit=min(500,max(1,(int)($_GET['limit']??200)));json_out(['data'=>$pdo->query("SELECT l.*,u.username,u.full_name FROM login_logs l LEFT JOIN users u ON u.id=l.user_id ORDER BY l.created_at DESC LIMIT $limit")->fetchAll()]);}
    if($action==='settings'){require_auth(['super_admin','admin']);$rows=$pdo->query('SELECT setting_key,setting_value,updated_at FROM settings ORDER BY setting_key')->fetchAll();$out=[];foreach($rows as $r)$out[$r['setting_key']]=$r['setting_value'];json_out(['data'=>$out]);}
    if($action==='archives'){require_auth(['super_admin','admin','auditor']);$limit=min(500,max(1,(int)($_GET['limit']??250)));$s=$pdo->query("SELECT a.*,u.username,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT $limit");json_out(['data'=>$s->fetchAll()]);}
    if($action==='my_archive'){ $limit=min(300,max(1,(int)($_GET['limit']??200)));$s=$pdo->prepare("SELECT id,action,entity,entity_id,old_value,new_value,reason,created_at FROM audit_logs WHERE user_id=? ORDER BY created_at DESC LIMIT $limit");$s->execute([$u['id']]);json_out(['data'=>$s->fetchAll()]);}
    if($action==='enrollments'){ $term=(int)($_GET['term_id']??0);$s=$pdo->prepare("SELECT e.*,s.full_name student_name,s.date_of_birth,c.name course_name,c.level_name,t.name term_name FROM enrollments e JOIN students s ON s.id=e.student_id JOIN courses c ON c.id=e.course_id JOIN terms t ON t.id=e.term_id WHERE e.term_id=? ORDER BY c.name,s.full_name");$s->execute([$term]);json_out(['data'=>$s->fetchAll()]);}
    if($action==='conflicts'){ $term=(int)($_GET['term_id']??0);$sql="SELECT e1.student_id,s.full_name student_name,se1.session_date,se1.start_time,se1.end_time,c1.name course_one,c2.name course_two FROM enrollments e1 JOIN enrollments e2 ON e2.student_id=e1.student_id AND e2.term_id=e1.term_id AND e2.id>e1.id JOIN students s ON s.id=e1.student_id JOIN schedule_entries se1 ON se1.term_id=e1.term_id AND se1.term_course_id IN (SELECT id FROM term_courses WHERE course_id=e1.course_id AND term_id=e1.term_id) JOIN schedule_entries se2 ON se2.term_id=e2.term_id AND se2.term_course_id IN (SELECT id FROM term_courses WHERE course_id=e2.course_id AND term_id=e2.term_id) AND se2.session_date=se1.session_date AND se2.start_time < se1.end_time AND se2.end_time > se1.start_time JOIN courses c1 ON c1.id=e1.course_id JOIN courses c2 ON c2.id=e2.course_id WHERE e1.term_id=? AND e1.status='active' AND e2.status='active' ORDER BY se1.session_date,se1.start_time";$s=$pdo->prepare($sql);$s->execute([$term]);json_out(['data'=>$s->fetchAll()]);}
    if($action==='term_days'){$term=(int)($_GET['term_id']??0);json_out(['data'=>schedule_dates($pdo,$term)]);}
    if($action==='print'){$term=(int)($_GET['term_id']??0);$sort=$_GET['sort']??'time';$allowed=['time'=>'se.session_date,se.start_time,c.name','course'=>'c.name,se.session_date,se.start_time','trainer'=>'t.full_name,se.session_date,se.start_time','status'=>'se.status,se.session_date,se.start_time'];$order=$allowed[$sort]??$allowed['time'];$s=$pdo->prepare("SELECT se.*,c.name course_name,c.code course_code,c.level_name,t.full_name trainer_name,(SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id AND e.term_id=se.term_id AND e.status='active') student_count FROM schedule_entries se JOIN term_courses tc ON tc.id=se.term_course_id JOIN courses c ON c.id=tc.course_id LEFT JOIN trainers t ON t.id=se.trainer_id WHERE se.term_id=? AND se.status IN ('proposed','approved','published') ORDER BY $order");$s->execute([$term]);json_out(['data'=>$s->fetchAll()]);}
}

if($method==='POST'){
    require_csrf();$d=body();$pdo=db();
    if($action==='calculate_term'){$start=$d['start_date']??'';$days=max(1,(int)($d['required_teaching_days']??setting('term_teaching_days','20')));$exclude=(bool)($d['exclude_friday']??(int)setting('exclude_friday','1'));if(!$start)json_out(['error'=>'start_date required'],422);$end=calculate_term_end($start,$days,$exclude);json_out(['end_date'=>$end,'days'=>schedule_dates_from_values($start,$end,$days,$exclude,$pdo)]);}
    if($action==='create_term'){require_auth(['super_admin','admin','course_manager','data_entry']);$name=trim((string)($d['name']??''));$start=$d['start_date']??'';$days=max(1,(int)($d['required_teaching_days']??setting('term_teaching_days','20')));$exclude=(int)($d['exclude_friday']??1);if(!$name||!$start)json_out(['error'=>'Term name and start date are required'],422);$end=calculate_term_end($start,$days,(bool)$exclude);$q=$pdo->prepare('INSERT INTO terms(term_number,name,academic_year,start_date,end_date,required_teaching_days,exclude_friday,status,notes) VALUES(?,?,?,?,?,?,?,\'draft\',?)');$termNo=(int)($d['term_number']??((int)$pdo->query('SELECT COALESCE(MAX(term_number),0)+1 FROM terms')->fetchColumn()));$q->execute([$termNo,$name,$d['academic_year']??date('Y'),$start,$end,$days,$exclude,$d['notes']??null]);$id=(int)$pdo->lastInsertId();audit('CREATE','term',$id,null,$d);json_out(['ok'=>true,'id'=>$id,'end_date'=>$end]);}
    if($action==='create_holiday'){require_auth(['super_admin','admin']);$q=$pdo->prepare('INSERT INTO holidays(holiday_date,name,holiday_type,notes) VALUES(?,?,?,?)');$q->execute([$d['holiday_date'],$d['name'],$d['holiday_type']??'official',$d['notes']??null]);audit('CREATE','holiday',(int)$pdo->lastInsertId(),null,$d);json_out(['ok'=>true]);}
    if($action==='create_level'){require_auth(['super_admin','admin','course_manager']);$q=$pdo->prepare('INSERT INTO levels(name,level_order) VALUES(?,?)');try{$q->execute([$d['name'],(int)$d['level_order']]);audit('CREATE','level',(int)$pdo->lastInsertId(),null,$d);json_out(['ok'=>true]);}catch(Throwable $e){json_out(['error'=>'Level name or order already exists'],409);}}
    if($action==='create_course'){require_auth(['super_admin','admin','course_manager','data_entry']);$q=$pdo->prepare('INSERT INTO courses(name,code,category,level_name,level_order,max_students,default_start,default_end,default_weekday,sessions_per_week,session_minutes,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$d['name'],$d['code']??null,$d['category']??null,$d['level_name'],$d['level_order']??1,$d['max_students']??25,$d['default_start']??null,$d['default_end']??null,$d['default_weekday']??null,$d['sessions_per_week']??3,$d['session_minutes']??120,$d['status']??'active',$d['notes']??null]);audit('CREATE','course',(int)$pdo->lastInsertId(),null,$d);json_out(['ok'=>true]);}
    if($action==='create_trainer'){require_auth(['super_admin','admin','course_manager','data_entry']);$q=$pdo->prepare('INSERT INTO trainers(full_name,email,country,country_code,phone,whatsapp,min_level_order,max_level_order,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?)');$q->execute([$d['full_name'],$d['email']??null,$d['country']??null,$d['country_code']??null,$d['phone']??null,$d['whatsapp']??null,$d['min_level_order']??1,$d['max_level_order']??6,$d['status']??'active',$d['notes']??null]);$id=(int)$pdo->lastInsertId();if(!empty($d['availability'])&&is_array($d['availability'])){foreach($d['availability'] as $a){$pdo->prepare('INSERT INTO trainer_availability(trainer_id,weekday,start_time,end_time) VALUES(?,?,?,?)')->execute([$id,(int)$a['weekday'],$a['start_time'],$a['end_time']]);}}audit('CREATE','trainer',$id,null,$d);json_out(['ok'=>true]);}
    if($action==='create_student'){require_auth(['super_admin','admin','course_manager','data_entry']);$q=$pdo->prepare('INSERT INTO students(student_code,full_name,date_of_birth,gender,country,country_code,phone,whatsapp,email,current_level_order,status,parent_name,parent_phone,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$d['student_code']??null,$d['full_name'],$d['date_of_birth']??null,$d['gender']??null,$d['country']??null,$d['country_code']??null,$d['phone']??null,$d['whatsapp']??null,$d['email']??null,$d['current_level_order']??1,$d['status']??'active',$d['parent_name']??null,$d['parent_phone']??null,$d['notes']??null]);audit('CREATE','student',(int)$pdo->lastInsertId(),null,$d);json_out(['ok'=>true]);}
    if($action==='enroll_student'){require_auth(['super_admin','admin','course_manager','data_entry']);$student=(int)$d['student_id'];$course=(int)$d['course_id'];$term=(int)$d['term_id'];$c=$pdo->prepare('SELECT max_students,status FROM courses WHERE id=?');$c->execute([$course]);$cr=$c->fetch();if(!$cr||$cr['status']!=='active')json_out(['error'=>'Course is not active'],422);$n=$pdo->prepare("SELECT COUNT(*) FROM enrollments WHERE course_id=? AND term_id=? AND status IN ('active','pending')");$n->execute([$course,$term]);if((int)$n->fetchColumn()>=(int)$cr['max_students'])json_out(['error'=>'Course capacity has been reached'],409);try{$pdo->prepare("INSERT INTO enrollments(student_id,course_id,term_id,status) VALUES(?,?,?,'active')")->execute([$student,$course,$term]);audit('ENROLL','enrollment',(int)$pdo->lastInsertId(),null,$d);json_out(['ok'=>true]);}catch(Throwable $e){json_out(['error'=>'Student is already enrolled in this course for this term'],409);}}
    if($action==='assign_courses'){require_auth(['super_admin','admin','course_manager']);$term=(int)$d['term_id'];foreach(($d['course_ids']??[]) as $cid){$q=$pdo->prepare("INSERT IGNORE INTO term_courses(term_id,course_id,preferred_weekday,preferred_start,preferred_end,sessions_per_week,status) SELECT ?,id,default_weekday,default_start,default_end,sessions_per_week,IF(status='suspended','suspended','pending') FROM courses WHERE id=?");$q->execute([$term,(int)$cid]);}audit('ASSIGN','term_courses',$term,null,['course_ids'=>$d['course_ids']??[]]);json_out(['ok'=>true]);}
    if($action==='save_settings'){require_auth(['super_admin','admin']);foreach(($d['settings']??[]) as $k=>$v){$q=$pdo->prepare('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$q->execute([$k,(string)$v]);}audit('UPDATE','settings',null,null,$d['settings']??[]);json_out(['ok'=>true]);}
    if($action==='generate_schedule'){
        require_auth(['super_admin','admin','course_manager']);$termId=(int)$d['term_id'];$simulate=!empty($d['simulate']);$gap=max(2,(int)setting('minimum_repeat_gap_terms','2'));$balance=(int)setting('balance_workload','1');$dates=schedule_dates($pdo,$termId);if(!$dates)json_out(['error'=>'No teaching dates found for term'],422);
        $cs=$pdo->prepare("SELECT tc.*,c.name,c.code,c.level_order,c.max_students,c.default_start,c.default_end,c.default_weekday,c.sessions_per_week,c.session_minutes FROM term_courses tc JOIN courses c ON c.id=tc.course_id WHERE tc.term_id=? AND tc.status='pending' AND c.status='active' ORDER BY c.level_order,c.name");$cs->execute([$termId]);$courses=$cs->fetchAll();$trainers=$pdo->query("SELECT * FROM trainers WHERE status='active' ORDER BY full_name")->fetchAll();$proposal=[];$unassigned=[];$load=[];$usedSlots=[];$proposedTrainerSlots=[];
        foreach($trainers as $t)$load[(int)$t['id']] = 0;
        $weeks=array_chunk($dates,5);
        foreach($courses as $c){
            $perWeek=max(1,(int)($c['sessions_per_week']?:3));
            $sessionMinutes=max(30,(int)($c['session_minutes']?:120));
            $start=$c['preferred_start']?:$c['default_start']?:'18:00:00';
            $end=$c['preferred_end']?:$c['default_end']?:date('H:i:s',strtotime($start)+$sessionMinutes*60);
            $weekdayPref=$c['preferred_weekday']!==null?(int)$c['preferred_weekday']:(int)($c['default_weekday']??0);
            $eligible=[];
            foreach($trainers as $t){
                if(!trainer_eligible($pdo,(int)$t['id'],(int)$c['level_order']))continue;
                if(course_history_blocked($pdo,(int)$t['id'],(int)$c['course_id'],$termId,$gap))continue;
                $eligible[]=$t;
            }
            if(!$eligible){$unassigned[]=['course_id'=>$c['course_id'],'course'=>$c['name'],'date'=>null,'reason'=>'No trainer is eligible under the level/repetition rules'];continue;}
            foreach($weeks as $week){
                $weekCandidates=$week;
                if($weekdayPref){$weekCandidates=array_values(array_filter($weekCandidates,function($date)use($weekdayPref){return (int)(new DateTimeImmutable($date))->format('N')===$weekdayPref;}));}
                if(!$weekCandidates)$weekCandidates=$week;
                usort($weekCandidates,function($a,$b)use($weekdayPref){if(!$weekdayPref)return strcmp($a,$b);$da=abs((int)(new DateTimeImmutable($a))->format('N')-$weekdayPref);$db=abs((int)(new DateTimeImmutable($b))->format('N')-$weekdayPref);return $da<=>$db;});
                $weekCandidates=array_slice($weekCandidates,0,$perWeek);
                foreach($weekCandidates as $date){
                    $weekday=(int)(new DateTimeImmutable($date))->format('N');$cands=[];
                    foreach($eligible as $t){$tid=(int)$t['id'];if(!trainer_available($pdo,$tid,$weekday,$start,$end))continue;$slotKey=$date.'|'.$start.'|'.$end.'|'.$tid;if(isset($usedSlots[$slotKey]))continue;if(trainer_conflict($pdo,$tid,$termId,$date,$start,$end))continue;$overlap=false;foreach(($proposedTrainerSlots[$tid][$date]??[]) as $ps){if($start<$ps['end'] && $end>$ps['start']){$overlap=true;break;}}if($overlap)continue;$cands[]=$t;}
                    if(!$cands){$unassigned[]=['course_id'=>$c['course_id'],'course'=>$c['name'],'date'=>$date,'reason'=>'No eligible trainer available for this date/time'];continue;}
                    usort($cands,function($a,$b)use(&$load,$balance){if($balance)return $load[(int)$a['id']]<=>$load[(int)$b['id']];return strcmp($a['full_name'],$b['full_name']);});
                    $t=$cands[0];$tid=(int)$t['id'];$load[$tid]++;$usedSlots[$date.'|'.$start.'|'.$end.'|'.$tid]=1;$proposedTrainerSlots[$tid][$date][]= ['start'=>$start,'end'=>$end];
                    $proposal[]=['term_id'=>$termId,'term_course_id'=>(int)$c['id'],'course_id'=>(int)$c['course_id'],'course_name'=>$c['name'],'trainer_id'=>(int)$t['id'],'trainer_name'=>$t['full_name'],'session_date'=>$date,'weekday'=>$weekday,'start_time'=>$start,'end_time'=>$end];
                }
            }
        }
        if(!$simulate){$pdo->beginTransaction();try{$pdo->prepare("DELETE FROM schedule_entries WHERE term_id=? AND status='proposed'")->execute([$termId]);$ins=$pdo->prepare("INSERT INTO schedule_entries(term_id,term_course_id,trainer_id,session_date,session_index,weekday,start_time,end_time,status) VALUES(?,?,?,?,?,?,?,?, 'proposed')");foreach($proposal as $i=>$p)$ins->execute([$termId,$p['term_course_id'],$p['trainer_id'],$p['session_date'],$i+1,$p['weekday'],$p['start_time'],$p['end_time']]);$pdo->prepare("UPDATE term_courses SET status='scheduled' WHERE term_id=? AND status='pending'")->execute([$termId]);$pdo->commit();}catch(Throwable $e){$pdo->rollBack();json_out(['error'=>'Generation failed','detail'=>$e->getMessage()],500);}audit('GENERATE','schedule',$termId,null,['created'=>count($proposal),'unassigned'=>$unassigned,'simulate'=>false]);}
        json_out(['ok'=>true,'simulate'=>$simulate,'created'=>count($proposal),'unassigned'=>$unassigned,'proposal'=>$proposal,'trainer_load'=>$load]);
    }
    if($action==='approve_schedule'){require_auth(['super_admin','admin']);$term=(int)$d['term_id'];$q=$pdo->prepare("UPDATE schedule_entries SET status='approved' WHERE term_id=? AND status='proposed'");$q->execute([$term]);audit('APPROVE','schedule',$term,null,['rows'=>$q->rowCount()]);json_out(['ok'=>true,'rows'=>$q->rowCount()]);}
    if($action==='publish_schedule'){require_auth(['super_admin','admin']);$term=(int)$d['term_id'];$q=$pdo->prepare("UPDATE schedule_entries SET status='published' WHERE term_id=? AND status IN ('proposed','approved')");$q->execute([$term]);audit('PUBLISH','schedule',$term,null,['rows'=>$q->rowCount()]);json_out(['ok'=>true,'rows'=>$q->rowCount()]);}
    if($action==='override'){require_auth(['super_admin','admin']);$id=(int)$d['schedule_entry_id'];$reason=trim((string)($d['reason']??''));if(!$reason)json_out(['error'=>'Override reason is required'],422);$pdo->prepare('UPDATE schedule_entries SET override_flag=1,override_reason=? WHERE id=?')->execute([$reason,$id]);$pdo->prepare('INSERT INTO overrides(schedule_entry_id,user_id,rule_name,reason) VALUES(?,?,?,?)')->execute([$id,$u['id'],$d['rule_name']??'manual_override',$reason]);audit('OVERRIDE','schedule_entry',$id,null,['reason'=>$reason],$reason);json_out(['ok'=>true]);}
    if($action==='upload_ocr'){
        require_auth(['super_admin','admin','course_manager','data_entry']);if(empty($_FILES['file']))json_out(['error'=>'File required'],422);$f=$_FILES['file'];if($f['error']!==UPLOAD_ERR_OK)json_out(['error'=>'Upload failed'],422);if($f['size']>15*1024*1024)json_out(['error'=>'Maximum file size is 15MB'],422);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','application/pdf'=>'pdf'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if(!isset($allowed[$mime]))json_out(['error'=>'Only JPG, PNG and PDF files are supported'],422);$name=bin2hex(random_bytes(16)).'.'.$allowed[$mime];$dest=dirname(__DIR__).'/storage/ocr/'.$name;if(!move_uploaded_file($f['tmp_name'],$dest))json_out(['error'=>'Could not store file'],500);$text='';$status='uploaded';if(envv('TESSERACT_BIN')){$cmd=escapeshellcmd(envv('TESSERACT_BIN')).' '.escapeshellarg($dest).' stdout 2>/dev/null';$text=(string)shell_exec($cmd);$status='reviewed';}else{$text='OCR engine is not configured. Install Tesseract and set TESSERACT_BIN in .env, or review the uploaded document manually.';}$q=$pdo->prepare('INSERT INTO ocr_imports(user_id,original_name,stored_path,source_type,extracted_text,status) VALUES(?,?,?,?,?,?)');$q->execute([$u['id'],$f['name'],$dest,$mime,$text,$status]);audit('OCR','ocr_import',(int)$pdo->lastInsertId(),null,['original_name'=>$f['name'],'mime'=>$mime]);json_out(['ok'=>true,'text'=>$text,'status'=>$status]);}
}

function schedule_dates_from_values(string $start,string $end,int $days,bool $excludeFriday, PDO $pdo): array { $hol=[];$q=$pdo->query("SELECT holiday_date FROM holidays WHERE active=1");foreach($q as $r)$hol[$r['holiday_date']]=1;$out=[];$d=new DateTimeImmutable($start);$e=new DateTimeImmutable($end);while($d<=$e && count($out)<$days){$key=$d->format('Y-m-d');$n=(int)$d->format('N');if(!($excludeFriday&&$n===5)&&!isset($hol[$key]))$out[]=$key;$d=$d->modify('+1 day');}return $out;}

json_out(['error'=>'Unknown action'],404);
